### ISSUE TITLE
No module named 'src'

### ISSUE THREAD

**Issue by NostalgiaRealm** [frankvollebregt/GBSPConverter#6]
Hey there, thanks for developing this converter!
 I am trying to convert a Genesis3D .bsp file using your script gbsp_to_ibsp.py
However the script is not running on my machine. It will immediately fail with below error. I am running Ubuntu 23.04 with python3 and pillow installed.

```
~/GBSPConverter/src$ python3 gbsp_to_ibsp.py
Traceback (most recent call last):
  File "/home/rick/GBSPConverter/src/gbsp_to_ibsp.py", line 1, in <module>
    from src.gbsp import GBSPChunk
ModuleNotFoundError: No module named 'src'
```

Thanks in advance for any insights!

**Comment by frankvollebregt** [comment]
Hey! Nice to see someone trying to use the program ;)

I just tried to run your command, and I'm running into the same issue now... ~I'll have a look tomorrow to see if I can resolve it.~

I've developed the program in PyCharm (on Windows), I guess PyCharm looks differently at the imports and their locations...

**Comment by frankvollebregt** [comment]
In a branch I just removed all the `src.` prefixes from the imports, and it seems to work. I'll have to look into it a bit, but at least you can try it then.

https://github.com/frankvollebregt/GBSPConverter/tree/src-import-fix

Let me know if it runs now :) I'll probably update main with these changes later this week

**Comment by NostalgiaRealm** [comment]
Thanks for getting back at me so quickly! I have succesfully converted GBSP files to the IBSP format now with the gbsp_to_ibsp.py script.
However, I am trying to import the newly converted IBSP file into Quake map editors such as The Quake Army Knife and BSP Quake Editor but none seem to be opening the files. Could you push me into the right direction on what could be used to open the maps into a map editor?

**Comment by frankvollebregt** [comment]
I'm afraid the ibsp files are not going to work directly: The script only converts the level geometry and textures, and not the BSP tree that is essentially the "skeleton" of the map file. 

The reason for that is that I was trying to convert the gbsp files into files that could be read with "modern" tools or game engines. I have successfully used a program called Noesis to open the resulting files. I'm not sure if these tools can "calculate" the BSP tree for you.

I haven't looked too much into converting the BSP tree within the script, part of it is likely quite easy, but other chunks would require quite more work...

Though not ideal, perhaps you can go through an OBJ file (or FBX, which is in its own branch), and either import that directly or convert it to an ibsp through another tool.

**Comment by NostalgiaRealm** [comment]
Ah I see, so it will definitely need more work to get a usable map in a modern engine out of the GBSP files than I initially thought. This knowledge is above my pay-grade for now, so I unfortunately will have to cease my efforts into getting any of this to work for now. I did get a somewhat usable output when converting to OBJ-files, Noesis was able to open the resulting files without issues but this only exports the geometry of the maps while I was wishing to achieve more. Still thanks a lot for the information and providing these scripts! I might at some point get back at this when I have more knowledge ;)
